### ISSUE TITLE
Not able to use without Column or Row

### ISSUE THREAD

**Issue by C4s4r** [smokelaboratory/motion_widget#5]
I hope that I've not overlooked something but it seems like it's not possible to use the animations without creating an extra Column or Row.
Would it be possible to implement the feature to use these animations for a single widget (without creating a Column/Row)?

Besides this the package is awesome - thanks for sharing!

**Comment by smokelaboratory** [comment]
Hi there! Thanks for reaching out.
This package is designed to solve the relative animation issue between multiple widgets. Hence, a column/row is required. For single widget, we can use Flutter's default animation class.
